version: "3.7"
services:
    cgit:
        build: .
        ports:
            - "22:22"
            - "80:80"
        volumes:
            - "./cgit-config:/etc/cgit.d"
            - "./ssh:/etc/ssh"
            - "./git.home:/git"
            - "./repos:/pub/git"

